# Generated by Django 4.2.5 on 2023-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_album_songs_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
