# Generated by Django 4.2.5 on 2023-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_band_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
