# Generated by Django 4.2.5 on 2023-11-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
