# Generated by Django 4.2.5 on 2023-11-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_song_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
